package com.maro.core.database

import androidx.room3.ConstructedBy
import androidx.room3.Database
import androidx.room3.RoomDatabase
import androidx.room3.RoomDatabaseConstructor
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import com.maro.core.database.chat.ChatDao
import com.maro.core.database.chat.ChatEntity
import kotlinx.coroutines.Dispatchers

@Database(entities = [ChatEntity::class], version = 1, exportSchema = true)
@ConstructedBy(MaroDatabaseConstructor::class)
abstract class MaroDatabase : RoomDatabase() {
    abstract fun chatDao(): ChatDao
}

/** The `actual` is generated by the Room/KSP compiler for each target (Android, iOS) — never written by hand. */
expect object MaroDatabaseConstructor : RoomDatabaseConstructor<MaroDatabase> {
    override fun initialize(): MaroDatabase
}

internal const val DATABASE_FILE_NAME = "maro.db"

/** Common builder configuration shared by every platform. */
internal fun RoomDatabase.Builder<MaroDatabase>.withDefaults(): MaroDatabase =
    setDriver(BundledSQLiteDriver())
        .setQueryCoroutineContext(Dispatchers.IO)
        .build()
